[2025-02-15T22:17:25.043+0100] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-15T22:17:25.054+0100] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_get_info_from_mongo.task_get_data scheduled__2025-02-15T21:16:00+00:00 [queued]>
[2025-02-15T22:17:25.061+0100] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_get_info_from_mongo.task_get_data scheduled__2025-02-15T21:16:00+00:00 [queued]>
[2025-02-15T22:17:25.062+0100] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-15T22:17:25.080+0100] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): task_get_data> on 2025-02-15 21:16:00+00:00
[2025-02-15T22:17:25.084+0100] {standard_task_runner.py:72} INFO - Started process 5589 to run task
[2025-02-15T22:17:25.088+0100] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'test_get_info_from_mongo', 'task_get_data', 'scheduled__2025-02-15T21:16:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/test_42stats.py', '--cfg-path', '/tmp/tmp9hpu3fxy']
[2025-02-15T22:17:25.090+0100] {standard_task_runner.py:105} INFO - Job 18: Subtask task_get_data
[2025-02-15T22:17:25.135+0100] {task_command.py:467} INFO - Running <TaskInstance: test_get_info_from_mongo.task_get_data scheduled__2025-02-15T21:16:00+00:00 [running]> on host n97
[2025-02-15T22:17:25.206+0100] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='test_get_info_from_mongo' AIRFLOW_CTX_TASK_ID='task_get_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-15T21:16:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-15T21:16:00+00:00'
[2025-02-15T22:17:25.207+0100] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-15T22:17:26.016+0100] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/wolfframio/Coding/Airflow/dags/test_42stats.py", line 18, in get_data
    result['task_instance'].xcom_push(
KeyError: 'task_instance'
[2025-02-15T22:17:26.024+0100] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=test_get_info_from_mongo, task_id=task_get_data, run_id=scheduled__2025-02-15T21:16:00+00:00, execution_date=20250215T211600, start_date=20250215T211725, end_date=20250215T211726
[2025-02-15T22:17:26.063+0100] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-15T22:17:26.064+0100] {standard_task_runner.py:124} ERROR - Failed to execute job 18 for task task_get_data ('task_instance'; 5589)
Traceback (most recent call last):
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/wolfframio/Coding/Airflow/dags/test_42stats.py", line 18, in get_data
    result['task_instance'].xcom_push(
KeyError: 'task_instance'
[2025-02-15T22:17:26.106+0100] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-15T22:17:26.125+0100] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-15T22:17:26.126+0100] {local_task_job_runner.py:245} INFO - ::endgroup::
