[2025-02-16T00:17:29.317+0100] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-16T00:17:29.329+0100] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 42stats_update_db.send_init_email scheduled__2025-02-14T22:00:00+00:00 [queued]>
[2025-02-16T00:17:29.336+0100] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 42stats_update_db.send_init_email scheduled__2025-02-14T22:00:00+00:00 [queued]>
[2025-02-16T00:17:29.336+0100] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-16T00:17:29.354+0100] {taskinstance.py:2890} INFO - Executing <Task(EmailOperator): send_init_email> on 2025-02-14 22:00:00+00:00
[2025-02-16T00:17:29.358+0100] {standard_task_runner.py:72} INFO - Started process 7931 to run task
[2025-02-16T00:17:29.362+0100] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', '42stats_update_db', 'send_init_email', 'scheduled__2025-02-14T22:00:00+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/42stats_get_levels.py', '--cfg-path', '/tmp/tmp9blocksy']
[2025-02-16T00:17:29.365+0100] {standard_task_runner.py:105} INFO - Job 30: Subtask send_init_email
[2025-02-16T00:17:29.409+0100] {task_command.py:467} INFO - Running <TaskInstance: 42stats_update_db.send_init_email scheduled__2025-02-14T22:00:00+00:00 [running]> on host n97
[2025-02-16T00:17:29.455+0100] {abstractoperator.py:783} ERROR - Exception rendering Jinja template for task 'send_init_email', field 'html_content'. Template: "\n42stats Report\n\n================================\nTask executed at: {{ execution_date.strftime('%Y-%m-%d %H:%M:%S' }}\n================================\n\n"
Traceback (most recent call last):
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 775, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/template/templater.py", line 170, in render_template
    template = jinja_env.from_string(value)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/jinja2/environment.py", line 1111, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/jinja2/environment.py", line 771, in compile
    self.handle_exception(source=source_hint)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 5, in template
jinja2.exceptions.TemplateSyntaxError: unexpected '}', expected ')'
[2025-02-16T00:17:29.457+0100] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3117, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context, jinja_env=jinja_env)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3540, in render_templates
    original_task.render_template_fields(context, jinja_env)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1442, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 775, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/template/templater.py", line 170, in render_template
    template = jinja_env.from_string(value)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/jinja2/environment.py", line 1111, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/jinja2/environment.py", line 771, in compile
    self.handle_exception(source=source_hint)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 5, in template
jinja2.exceptions.TemplateSyntaxError: unexpected '}', expected ')'
[2025-02-16T00:17:29.462+0100] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=42stats_update_db, task_id=send_init_email, run_id=scheduled__2025-02-14T22:00:00+00:00, execution_date=20250214T220000, start_date=20250215T231729, end_date=20250215T231729
[2025-02-16T00:17:29.490+0100] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-16T00:17:29.490+0100] {standard_task_runner.py:124} ERROR - Failed to execute job 30 for task send_init_email (unexpected '}', expected ')'; 7931)
Traceback (most recent call last):
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3117, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context, jinja_env=jinja_env)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3540, in render_templates
    original_task.render_template_fields(context, jinja_env)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1442, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 775, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/template/templater.py", line 170, in render_template
    template = jinja_env.from_string(value)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/jinja2/environment.py", line 1111, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/jinja2/environment.py", line 771, in compile
    self.handle_exception(source=source_hint)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 5, in template
jinja2.exceptions.TemplateSyntaxError: unexpected '}', expected ')'
[2025-02-16T00:17:29.535+0100] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-16T00:17:29.566+0100] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-16T00:17:29.576+0100] {local_task_job_runner.py:245} INFO - ::endgroup::
