[2025-02-15T20:59:16.255+0100] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-15T20:59:16.270+0100] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: prueba_simple.enviar_email scheduled__2025-02-15T19:58:00+00:00 [queued]>
[2025-02-15T20:59:16.278+0100] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: prueba_simple.enviar_email scheduled__2025-02-15T19:58:00+00:00 [queued]>
[2025-02-15T20:59:16.279+0100] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-15T20:59:16.298+0100] {taskinstance.py:2890} INFO - Executing <Task(EmailOperator): enviar_email> on 2025-02-15 19:58:00+00:00
[2025-02-15T20:59:16.302+0100] {standard_task_runner.py:72} INFO - Started process 9770 to run task
[2025-02-15T20:59:16.306+0100] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'prueba_simple', 'enviar_email', 'scheduled__2025-02-15T19:58:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp2v_routk']
[2025-02-15T20:59:16.308+0100] {standard_task_runner.py:105} INFO - Job 9: Subtask enviar_email
[2025-02-15T20:59:16.351+0100] {task_command.py:467} INFO - Running <TaskInstance: prueba_simple.enviar_email scheduled__2025-02-15T19:58:00+00:00 [running]> on host n97
[2025-02-15T20:59:16.434+0100] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='prueba_simple' AIRFLOW_CTX_TASK_ID='enviar_email' AIRFLOW_CTX_EXECUTION_DATE='2025-02-15T19:58:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-15T19:58:00+00:00'
[2025-02-15T20:59:16.435+0100] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-15T20:59:16.461+0100] {logging_mixin.py:190} WARNING - /home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/utils/email.py:155 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2025-02-15T20:59:16.462+0100] {email.py:272} INFO - Email alerting: attempt 1
[2025-02-15T20:59:23.461+0100] {local_task_job_runner.py:127} ERROR - Received SIGTERM. Terminating subprocesses
[2025-02-15T20:59:23.500+0100] {process_utils.py:132} INFO - Sending 15 to group 9770. PIDs of all processes in the group: [9770]
[2025-02-15T20:59:23.501+0100] {process_utils.py:87} INFO - Sending the signal 15 to group 9770
[2025-02-15T20:59:26.613+0100] {taskinstance.py:3094} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-02-15T20:59:26.624+0100] {taskinstance.py:3095} ERROR - Stacktrace: 
  File "/home/wolfframio/miniforge3/envs/airflow_env/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/__main__.py", line 62, in main
    args.func(args)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 254, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 322, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/jobs/job.py", line 421, in run_job
    return execute_job(job, execute_callable=execute_callable)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/jobs/job.py", line 450, in execute_job
    ret = execute_callable()
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/jobs/local_task_job_runner.py", line 171, in _execute
    self.task_runner.start()
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 55, in start
    self.process = self._start_by_fork()
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/operators/email.py", line 79, in execute
    send_email(
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/utils/email.py", line 155, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/utils/email.py", line 274, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/utils/email.py", line 318, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/smtplib.py", line 265, in __init__
    fqdn = socket.getfqdn()
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/socket.py", line 804, in getfqdn
    hostname, aliases, ipaddrs = gethostbyaddr(name)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3095, in signal_handler
    self.log.error("Stacktrace: \n%s", "".join(traceback.format_stack()))

[2025-02-15T20:59:26.630+0100] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/socket.py", line 804, in getfqdn
    hostname, aliases, ipaddrs = gethostbyaddr(name)
socket.herror: [Errno 2] Host name lookup failure

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/operators/email.py", line 79, in execute
    send_email(
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/utils/email.py", line 155, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/utils/email.py", line 274, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/utils/email.py", line 318, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/smtplib.py", line 265, in __init__
    fqdn = socket.getfqdn()
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/socket.py", line 804, in getfqdn
    hostname, aliases, ipaddrs = gethostbyaddr(name)
  File "/home/wolfframio/miniforge3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3097, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2025-02-15T20:59:26.633+0100] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=prueba_simple, task_id=enviar_email, run_id=scheduled__2025-02-15T19:58:00+00:00, execution_date=20250215T195800, start_date=20250215T195916, end_date=20250215T195926
[2025-02-15T20:59:26.663+0100] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-15T20:59:26.701+0100] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-15T20:59:26.708+0100] {taskinstance.py:2604} INFO - Dependencies not met for <TaskInstance: prueba_simple.enviar_email scheduled__2025-02-15T19:58:00+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2025-02-15T20:59:26.717+0100] {local_task_job_runner.py:166} INFO - Task is not able to be run
